apiVersion: batch/v1
kind: Job
metadata:
  name: configure-cp4i-network-policy
  annotations:
    argocd.argoproj.io/hook: PreSync
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "96Mi"
              cpu: "300m"
          command:
            - /bin/sh
            - -c
            - |
              oc create secret docker-registry ibm-entitlement-key \       
                --docker-username=cp \
                --docker-password=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE2MDc1MjI4MTUsImp0aSI6IjM5MDBmMjIzYTQ0NjQzZWY5YWI0YjU0MjY3ZDc5MGJmIn0.3EDG4APxK5NhJQ6_xWSsZEw-D45IVmfJr9x525Tqtug \
                --docker-server=cp.icr.io \
                --namespace=cp4i
