apiVersion: batch/v1
kind: Job
metadata:
  name: configure-cp4i-network-policy
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "96Mi"
              cpu: "300m"
          command:
            - /bin/sh
            - -c
            - |
              oc get secret ibm-entitlement-key -n openshift-gitops -o json > entitlement.json 
              sed -i 's/openshift-gitops/cp4i/g' entitlement.json 
              sed -i '/resource/d' entitlement.json 
              sed -i '/uid/d' entitlement.json
              cat entitlement.json
              oc apply -f entitlement.json
      restartPolicy: Never 
      serviceAccountName: openshift-gitops-argocd-application-controller
