apiVersion: batch/v1
kind: Job
metadata:
  name: add-ibm-entitlement-secret
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              oc get secret ibm-entitlement-key -n openshift-gitops -o yaml > entitlement.yaml  
              sed -i 's/openshift-gitops/cp4i/g' entitlement.yaml 
              sed -i '/resource/d' entitlement.yaml 
              sed -i '/uid/d' entitlement.yaml
              sed -i '/creation/d' entitlement.yaml
              oc apply -f entitlement.yaml
      restartPolicy: Never 
      serviceAccountName: openshift-gitops-argocd-application-controller
