apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-automation-core.openshift-operators: ''
  name: ibm-automation-core
  namespace: openshift-operators
spec:
  channel: v1.2
  installPlanApproval: Automatic
  name: ibm-automation-core
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
