apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datapower-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/datapower-operator.openshift-operators: ''
spec:
  channel: v1.4
  installPlanApproval: Automatic
  name: datapower-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace