apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base
  namespace: openshift-gitops
spec:
  generators:
    - git:
        directories:
        - path: base/*
        repoURL: 'https://github.com/jtarte/gitops'
        revision: gitops-test-b
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: default
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/jtarte/gitops'
        targetRevision: gitops-test-b
      syncPolicy:
        automated:
          prune: true
          selfHeal: true