apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: test-is
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-KSBM-C37J2R
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: 'jtarte/testbar:latest'
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  adminServerSecure: false
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  version: 12.0.1.0-r2
  replicas: 1
  configurations:
    - mqpolicy