apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-mvp-configmap
  annotations:
    argocd.argoproj.io/sync-wave: "30"
data:
  bahbrkp1.mqsc: |
    Define QL(TIME.DEP.DET.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(TIME.DEP.DET.REQ.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(TIME.DEP.DET.REP.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(TIME.DEP.DET.REP.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(TEST.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(TEST) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STMT.LIST.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.CC.AUTH.INQ.SUM.REQ.OUT) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.CC.AUTH.INQ.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.CC.AUTH.INQ.REP.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.CC.AUTH.INQ.REP.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.CC.AUTH.INQ.DET.REQ.OUT) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.CC.AUTH.INQ.DET.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.CC.AUTH.INQ.DET.REQ.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.ACC.BAL.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.ACC.BAL.REQ.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.ACC.BAL.REP.UNKNOWN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.ACC.BAL.REP.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(STD.ACC.BAL.REP.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(RETAIL.ACC.ACT.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(RETAIL.ACC.ACT.REP.STORE) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(RETAIL.ACC.ACT.REP.OUT) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(RETAIL.ACC.ACT.REP.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(MOBILE.WS.REP) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(LOAN.DET.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(LOAN.DET.REQ.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(LOAN.DET.REP.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(LOAN.DET.REP.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ERROR.TESTING.AGG) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(CHQ.STAT.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(CHQ.STAT.REQ.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(CHQ.STAT.REP.OUT) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(CHQ.STAT.REP.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(CHQ.STAT.REP.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(CC.BAL.REQ.OUT) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(BROKER.MSG.STORE) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(AUDIT.DB.REQ.LOG) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(AUDIT.DB.REQ.IN.ALIAS) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(AUDIT.DB.REQ.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(AGG.TEST) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.DET.REQ.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.DET.REQ.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.DET.REP.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.DET.REP.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.DET.AGG.TEST.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.BAL.AGG.TEST.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.ACT.REQ.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.ACT.AGG.TEST.IN) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(ACC.ACT.REP.FAIL) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    Define QL(BP.REQ) DEFPSIST(YES) MAXDEPTH(1000000) MAXMSGL(41943040) REPLACE
    
    DEFINE QALIAS (BP1.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP2.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP3.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP4.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP5.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP6.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP7.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP8.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP9.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP10.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP11.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP12.REQ) TARGET (BP.REQ) REPLACE
    DEFINE QALIAS (BP13.REQ) TARGET (BP.REQ) REPLACE

    DEFINE CHANNEL(SVR.CONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) DESCR('Server-connection to Client_2')  REPLACE

    DEFINE CHANNEL(APPCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')  REPLACE
    SET CHLAUTH(APPCHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)

    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(NONE) CHCKLOCL(NONE) 
    
    set chlauth(system.*) type(addressmap) address(*) action(remove)
    set chlauth(*) type(blockuser) userlist(*mqadmin) action(remove)
    set chlauth(system.def.svrconn) type(addressmap) address(*) mcauser (admin) action(add)
    
    REFRESH SECURITY

  bahbrkp1.ini: |
    Log:
      LogPrimaryFiles=10
      LogSecondaryFiles=3
      LogFilePages=16384
      LogBufferPages=4096
    Channels:
      MaxChannels=2000
      MaxActiveChannels=2000
    QMErrorLog:
      ErrorLogSize=2048000
    TCP:
      KeepAlive=Yes

  