apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-mvp-certificate
spec:
  # name of the tls secret to store
  # the generated certificate/key pair
  secretName: mq-mvp-instance-tls
  issuerRef:
    # Issuer Name
    name: cs-clusterissuer
    # The default value is Issuer (i.e.
    # a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: "bahbrkp1"
  privateKey:
    algorithm: RSA
    size: 2048