{
 "title": "mq ace dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "qmgr", "label": "qmgr", "query": "ibmmq_qmgr_status" },
   {
    "name": "pod",
    "label": "IS container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"},container)"
   }
  ]
 },
 "panels": [
  {
   "title": "QMGRs pod cpu usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container=\"qmgr\"}[2m]))"
    }
   ]
  },
  {
   "title": "QMGRs pod memory usage (Mib)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container=\"qmgr\"}) / 1048576"
    }
   ]
  },
  {
   "title": "messages handled by flow",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "ibmace_msgflow_messages_total{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "QMGR uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_uptime{namespace=~\"$namespace\",qmgr=~\"$qmgr\"}"
    }
   ]
  },
  {
   "title": "Queue depth",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_depth{namespace=~\"$namespace\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Integration Server pod cpu usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container=~\"$pod\"}[2m]))"
    }
   ]
  }
 ]
}